#!/bin/bash

echo "updating package lists"
sudo apt-get update

if [[ "$OSTYPE" == "darwin"* ]]; then
  echo "installing brew, tmux, ripgrep, starship, grc"
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
  brew cask install iterm2
  brew install tmux
  brew install ripgrep
  brew install starship
  brew install grc
  brew install httpie
elif [[ "$OSTYPE" == "linux-gnu"* ]]; then
  echo "installing tmux, ripgrep, starship, grc"
  sudo apt-get install tmux
  sudo chmod +x ./rg
  sudo cp ./rg /usr/local/bin/rg
  sudo apt-get install starship
  sudo apt-get install grc
  sudo apt-get install httpie
fi

echo "installing vim, xclip"
sudo apt-get install vim
sudo apt-get install xclip

echo "installing ripgrep, fzf"
sudo chmod +x ./fzf
sudo cp ./fzf /usr/local/bin/fzf
echo "copying vim, tmux, bash, git config"
sudo cp ./.vimrc ~/.vimrc
sudo cp ./.tmux.conf ~/.tmux.conf
sudo cp ./.tmux.conf.local ~/.tmux.conf.local
sudo cp ./.bashrc ~/.bashrc
sudo cp ./.gitconfig ~/.gitconfig
sudo cp ./.gitignore_global ~/.gitignore_global

echo "installing nvm, node"
git clone https://github.com/creationix/nvm.git ~/.nvm
original_dir=$(pwd)
cd ~/.nvm
. nvm.sh
cd $original_dir
source ~/.bashrc
nvm install node
nvm use node
npm install -g babel-cli gulp gulp-cli prettier

echo "couple tweaks"
echo fs.inotify.max_user_watches=16384 | sudo tee -a /etc/sysctl.conf
sudo sysctl -p

echo "finish!"
